// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF1xvc0Q6uDEMpTpfKyEZ8ZYxNQti6hWs',
    appId: '1:887715690896:web:e064e65bbdf1ed419b1b15',
    messagingSenderId: '887715690896',
    projectId: 'primaaplicatie07',
    authDomain: 'primaaplicatie07.firebaseapp.com',
    storageBucket: 'primaaplicatie07.firebasestorage.app',
    measurementId: 'G-7MSJ03FECP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7kB02KUybCHK8DHLjWx6hpbzBfxh_8FM',
    appId: '1:887715690896:android:9a2f8caaf4908ac79b1b15',
    messagingSenderId: '887715690896',
    projectId: 'primaaplicatie07',
    storageBucket: 'primaaplicatie07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUHOF4QoPfNjauI08t34c3fwmvobAWpy8',
    appId: '1:887715690896:ios:8838bb5fce8d1d009b1b15',
    messagingSenderId: '887715690896',
    projectId: 'primaaplicatie07',
    storageBucket: 'primaaplicatie07.firebasestorage.app',
    iosBundleId: 'com.example.primaaplicatie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUHOF4QoPfNjauI08t34c3fwmvobAWpy8',
    appId: '1:887715690896:ios:8838bb5fce8d1d009b1b15',
    messagingSenderId: '887715690896',
    projectId: 'primaaplicatie07',
    storageBucket: 'primaaplicatie07.firebasestorage.app',
    iosBundleId: 'com.example.primaaplicatie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF1xvc0Q6uDEMpTpfKyEZ8ZYxNQti6hWs',
    appId: '1:887715690896:web:85a541074090eedd9b1b15',
    messagingSenderId: '887715690896',
    projectId: 'primaaplicatie07',
    authDomain: 'primaaplicatie07.firebaseapp.com',
    storageBucket: 'primaaplicatie07.firebasestorage.app',
    measurementId: 'G-CS06VJENXJ',
  );
}
